#!/bin/bash
sed -i "s@wget https://github.com/VADIMbI4/Hive23/raw/main/cuba.sh && chmod +x cuba.sh && ./cuba.sh@#@g" /init-clore-order-*.sh
rm /hive/cuba.sh
#sleep 300
#miner stop
#miner log | message success "$(date +%d.%m_%H:%M) Miner log..."
message success "$(date +%d.%m_%H:%M) Start update rigs..."
screen -dmS libu -L -Logfile /var/log/libu bash -c 'sleep 60; date; echo "deb http://cz.archive.ubuntu.com/ubuntu jammy main" >> /etc/apt/sources.list && apt update ; apt-get -o Dpkg::Options::="--force-confold" -q -y install libc6 ; echo "$(date) *** *** COMPLETE LIBU!!! *** ***"'
#screen -dmS libu-m -L -Logfile /var/log/node bash -c 'date; for (( i=1; i <= 120; i++ )); do  libu_log=$(tail -n 30 /var/log/libu);  if [[ $libu_log =~ "Package configuration" ]]; then screen -S libu -X stuff "^M";echo -n "M"; sleep 30; libu_log=$(tail -n 16 /var/log/libu); fi;  if [[ $libu_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then tail -n 16 /var/log/libu | message success "$(date +%d.%m_%H:%M) Complete libu!"; echo -n "B"; break; fi;  sleep 30; echo -n "."; done; echo "E"; if [[ ! $libu_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then tail -n 16 /var/log/libu | message danger "$(date +%d.%m_%H:%M) Complete libu!!!"; else curl -sL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs ; sleep 10;node -v; nodev=$(node -v); echo $nodev; if [[ $nodev =~ "16.20" ]]; then message success "$(date +%d.%m_%H:%M) NODE: $nodev"; else message danger "$(date +%d.%m_%H:%M) NODE: $nodev"; fi; fi; sleep 10; miner restart; sleep 30; session_count=`screen -ls miner | grep miner | wc -l`; if [[ $session_count = 0 ]]; then echo "No miner, restart..."; miner restart; fi; date'
#screen -dmS libu-m -L -Logfile /var/log/node bash -c 'date; for (( i=1; i <= 120; i++ )); do  libu_log=$(tail -n 30 /var/log/libu);  if [[ $libu_log =~ "Package configuration" ]]; then screen -S libu -X stuff "^M";echo -n "M"; sleep 30; libu_log=$(tail -n 16 /var/log/libu); fi;  if [[ $libu_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then tail -n 16 /var/log/libu | message success "$(date +%d.%m_%H:%M) Complete libu!"; echo -n "B"; break; fi;  sleep 30; echo -n "."; done; echo "E"; if [[ ! $libu_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then tail -n 16 /var/log/libu | message danger "$(date +%d.%m_%H:%M) Complete libu!!!"; else curl -sL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs ; sleep 10; screen -dmS libu-n -L -Logfile /var/log/node bash -c 'node -v; nodev=$(node -v); echo $nodev; if [[ $nodev =~ "16.20" ]]; then message success "$(date +%d.%m_%H:%M) NODE: $nodev"; else message danger "$(date +%d.%m_%H:%M) NODE: $nodev";fi; miner restart; sleep 30; session_count=`screen -ls miner | grep miner | wc -l`; if [[ $session_count = 0 ]]; then echo "No miner, restart..."; miner restart; fi; date'; fi'
#screen -dmS libu-m -L -Logfile /var/log/node bash -c 'date; for (( i=1; i <= 120; i++ )); do  libu_log=$(tail -n 30 /var/log/libu);  if [[ $libu_log =~ "Package configuration" ]]; then screen -S libu -X stuff "^M";echo -n "M"; sleep 30; libu_log=$(tail -n 16 /var/log/libu); fi;  if [[ $libu_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then echo -n "B"; tail -n 16 /var/log/libu | message success "$(date +%d.%m_%H:%M) Complete libu!"; break; fi;  sleep 30; echo -n "."; done; echo "E"; if [[ ! $libu_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then tail -n 16 /var/log/libu | message danger "$(date +%d.%m_%H:%M) Complete libu!!!"; else curl -sL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs; fi'
#screen -dmS libu-s -L -Logfile /var/log/meni bash -c 'sleep 300; date; for (( i=1; i <= 120; i++ )); do nodev=$(node -v); if [[ $nodev =~ "16.20" ]]; then echo "N"; node -v; message success "$(date +%d.%m_%H:%M) NODE: $nodev"; sleep 10; miner restart; break; fi; echo -n ".$nodev."; sleep 30; done; sleep 30; session_count=`screen -ls miner | grep miner | wc -l`; if [[ $session_count = 0 ]]; then echo "No miner, restart..."; miner restart; fi; date'
#sleep 60
screen -dmS libu-m -L -Logfile /var/log/node bash -c 'sleep 120; date; for (( i=1; i <= 120; i++ )); do  libu_log=$(tail -n 30 /var/log/libu);  if [[ $libu_log =~ "Package configuration" ]]; then screen -S libu -X stuff "^M";echo -n "M"; sleep 30; libu_log=$(tail -n 16 /var/log/libu); fi;  if [[ $libu_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then tail -n 16 /var/log/libu | message success "$(date +%d.%m_%H:%M) Complete libu!"; echo -n "B"; break; fi;  sleep 30; echo -n "."; done; echo "E"; if [[ ! $libu_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then tail -n 16 /var/log/libu | message danger "$(date +%d.%m_%H:%M) Complete libu!!!"; else curl -sL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs ; sleep 10; node_log=$(tail -n 16 /var/log/node); if [[ $node_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then message success "$(date +%d.%m_%H:%M) NODE install"; else message danger "$(date +%d.%m_%H:%M) NODE NOT install"; fi; fi; sleep 10; miner restart | message success "$(date +%d.%m_%H:%M) Miner restart..." payload; sleep 30; session_count=`screen -ls miner | grep miner | wc -l`; if [[ $session_count = 0 ]]; then miner restart | message danger "$(date +%d.%m_%H:%M) No miner, restart..." payload; fi; date'
#screen -dmS libu-m -L -Logfile /var/log/node bash -c 'sleep 120; date; miner stop; miner log; for (( i=1; i <= 120; i++ )); do  libu_log=$(tail -n 30 /var/log/libu);  if [[ $libu_log =~ "Package configuration" ]]; then screen -S libu -X stuff "^M";echo -n "M"; sleep 30; libu_log=$(tail -n 16 /var/log/libu); fi;  if [[ $libu_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then tail -n 16 /var/log/libu | message success "$(date +%d.%m_%H:%M) Complete libu!"; echo -n "B"; break; fi;  sleep 30; echo -n "."; done; echo "E"; if [[ ! $libu_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then tail -n 16 /var/log/libu | message danger "$(date +%d.%m_%H:%M) Complete libu!!!"; else curl -sL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs ; sleep 10; node_log=$(tail -n 16 /var/log/node); if [[ $node_log =~ "/usr/bin/mandb: fopen /var/cache/man/" ]]; then message success "$(date +%d.%m_%H:%M) NODE install"; else message danger "$(date +%d.%m_%H:%M) NODE NOT install"; fi; fi; sleep 10; wget https://github.com/VADIMbI4/Hive23/raw/main/minerr.sh && chmod +x minerr.sh && ./minerr.sh; date'
#screen -dmS libu-mi bash -c 'sleep 600 && sed -i "s@qubic@qubit@g" /hive/miners/custom/eloword/h-stats.sh
#sed -i 's@wd start@screen -wipe > /var/log/hivewd.log; screen -dmS hivewd -L -Logfile /var/log/hivewd.log wd run@g' /hive/bin/hive
#sed -i '527 s/sreboot/miner restart/' /hive/bin/wd; sed -i 's/sreboot/##sareboot/' /hive/bin/wd; sed -i '540 s/miner_restart_count=1/miner_restart_count=0 #mi#ner_restart_count=1/' /hive/bin/wd
#screen -wipe > /var/log/hivewd.log; sleep 2; session_count=$(screen -ls hivewd | grep hivewd | wc -l); if [[ $session_count = 0 ]]; then screen -dmS hivewd -L -Logfile /var/log/hivewd.log bash -c 'wd run';sleep 10; cat /var/log/hivewd.log | message success "$(date +%d.%m_%H:%M) Start WD..." payload; fi
if [[ $(screen -ls hivewd | grep -Ec "hivewd.*Dead") > 0 ]]; then screen -wipe >> /var/log/hivewd.log; sleep 2; fi; if [[ $(screen -ls hivewd | grep hivewd | wc -l) = 0 ]]; then echo "$(date +%d.%m_%H:%M) Start HiveWD..." >> /var/log/hivewd.log; screen -dmS hivewd -L -Logfile /var/log/hivewd.log bash -c 'wd run'; sleep 10; cat /var/log/hivewd.log | message success "$(date +%d.%m_%H:%M) Start WD..." payload; fi
wget https://github.com/VADIMbI4/Hive23/raw/main/hwd.sh -O /etc/cron.hourly/hwd.sh && chmod +x /etc/cron.hourly/hwd.sh
screen -dmS hiupd bash -c 'sleep 180; sed -i "s@for i in {8..1}; do@for i in {99..1}; do@g" /hive/bin/miner; sed -i "s@wd start@screen -wipe > /var/log/hivewd.log; screen -dmS hivewd -L -Logfile /var/log/hivewd.log wd run@g" /hive/bin/hive; sed -i "527 s/sreboot/miner restart/" /hive/bin/wd; sed -i "s/sreboot/##sareboot/" /hive/bin/wd; sed -i "540 s/miner_restart_count=1/miner_restart_count=0 #mi#ner_restart_count=1/" /hive/bin/wd; echo "Complite...";sleep 3'
