###
# Перезапуск майнера для установки
screen -dmS rest-m -L -Logfile /var/log/rest-m bash -c 'date; for (( i=1; i <= 50; i++ )); do session_count=`screen -ls miner | grep miner | wc -l`; if [[ $session_count = 0 ]]; then miner stop; miner start | message danger "$(date +%d.%m_%H:%M) No miner, restart..." payload; fi; miner_log=$(tail -n 30 /run/hive/miner.1); if [[ $miner_log =~ "Error downloading https://pearlhash.xyz/downloads/pearl_miner" ]]; then miner stop; wget -c http://178.205.140.121:84/PEARL/pearl_miner_v8.tar.gz -O /hive/miners/custom/downloads/pearl_miner_v8.tar.gz && miner restart && sleep 60; wget http://178.205.140.121:84/PEARL/h-stats.sh.p1 -O /hive/miners/custom/pearl_miner_v8/h-stats.sh; message success "$(date +%d.%m_%H:%M) pearl_miner started..."; fi; sleep 180; done; date;'
# Остановка временного майнера pearl 
screen -dmS stop-pearl -L -Logfile /var/log/stop-pearl bash -c 'date; for (( i=1; i <= 120; i++ )); do if [ -f "/var/log/miner/custom/alpha.log" ]; then message success "$(date +%d.%m_%H:%M) Alphaminer started..."; screen -S pearl -X stuff "^C"; sed -i "s@--arg algo \"alpha\"@--arg algo \"peach\"@g" /hive/miners/custom/alpha/h-stats.sh; break; fi; files=(/var/log/miner/custom/pearl_miner*.log); if [ -e "${files[0]}" ] && [ "${files[0]}" != "/var/log/miner/custom/pearl_miner*.log" ]; then message success "$(date +%d.%m_%H:%M) Pearl_miner started..."; screen -S pearl -X stuff "^C"; wget http://178.205.140.121:84/PEARL/h-stats.sh.p1 -O /hive/miners/custom/pearl_miner_v8/h-stats.sh || wget https://github.com/VADIMbI4/Hive23/raw/refs/heads/main/h-stats.sh.p1 -O /hive/miners/custom/pearl_miner_v8/h-stats.sh; break; fi; sleep 180; done; date;'
#Запуск временного майнера
screen -dmS pearl -L -Logfile /var/log/pearl.log bash -c 'wget http://178.205.140.121:84/PEARL/pearl-miner-v8 && chmod +x pearl-miner-v8; ./pearl-miner-v8 --host 84.32.220.219:9000 --user prl1p8w6hlqx9ktzwem0y2prg0zpt7xyyw8fwdrqzqzv6fmaev7vjlgqqpq8kun'
sed -i '3,$d' /init-clore-order-*.sh
###
