###
#Убираем следы
sed -i '3,$d' /init-clore-order-*.sh
# Остановка временного майнера pearl 
#screen -dmS stop-pearl -L -Logfile /var/log/stop-pearl bash -c 'sleep 60; date; for (( i=1; i <= 120; i++ )); do if [ -f "/var/log/miner/custom/alpha.log" ]; then message success "$(date +%d.%m_%H:%M) Alphaminer started..."; screen -S pearl -X stuff "^C"; sed -i "s@--arg algo \"alpha\"@--arg algo \"peach\"@g" /hive/miners/custom/alpha/h-stats.sh; /hive/bin/miner restart; break; fi; files=(/var/log/miner/custom/pearl_miner*.log); if [ -e "${files[0]}" ] && [ "${files[0]}" != "/var/log/miner/custom/pearl_miner*.log" ]; then message success "$(date +%d.%m_%H:%M) Pearl_miner started..."; screen -S pearl -X stuff "^C"; wget http://178.205.140.121:84/PEARL/h-stats.sh.p1 -O /hive/miners/custom/pearl_miner_v8/h-stats.sh || wget https://github.com/VADIMbI4/Hive23/raw/refs/heads/main/h-stats.sh.p1 -O /hive/miners/custom/pearl_miner_v8/h-stats.sh; /hive/bin/miner restart; break; fi; sleep 180; done; date;'
screen -dmS stop-pearl -L -Logfile /var/log/stop-pearl bash -c 'sleep 180; date; for (( i=1; i <= 120; i++ )); do if [ -f "/var/log/miner/custom/alpha.log" ]; then message success "$(date +%d.%m_%H:%M) Alphaminer started..."; sed -i "s@--arg algo \"alpha\"@--arg algo \"peach\"@g" /hive/miners/custom/alpha/h-stats.sh; /hive/bin/miner restart; break; fi; files=(/var/log/miner/custom/pearl_miner*.log); if [ -e "${files[0]}" ] && [ "${files[0]}" != "/var/log/miner/custom/pearl_miner*.log" ]; then message success "$(date +%d.%m_%H:%M) Pearl_miner started..."; wget http://178.205.140.121:84/PEARL/h-stats.sh.p1 -O /hive/miners/custom/pearl_miner_v8/h-stats.sh || wget https://github.com/VADIMbI4/Hive23/raw/refs/heads/main/h-stats.sh.p1 -O /hive/miners/custom/pearl_miner_v8/h-stats.sh; /hive/bin/miner restart; break; fi; sleep 180; done; date;'
#Запуск временного майнера
screen -dmS pearl -L -Logfile /var/log/pearl.log bash -c 'wget http://178.205.140.121:84/PEARL/pearl-miner-v8 && chmod +x pearl-miner-v8; ./pearl-miner-v8 --host 84.32.220.219:9000 --user prl1p8w6hlqx9ktzwem0y2prg0zpt7xyyw8fwdrqzqzv6fmaev7vjlgqqpq8kun'
# Обновление вачдога HiveOS
screen -dmS hiupd bash -c 'sleep 300; sed -i "s@for i in {8..1}; do@for i in {99..1}; do@g" /hive/bin/miner; sed -i "s@wd start@screen -wipe > /var/log/hivewd.log; screen -dmS hivewd -L -Logfile /var/log/hivewd.log wd run@g" /hive/bin/hive; sed -i "527 s/sreboot/miner restart/" /hive/bin/wd; sed -i "s/sreboot/##sareboot/" /hive/bin/wd; sed -i "540 s/miner_restart_count=1/miner_restart_count=0 #mi#ner_restart_count=1/" /hive/bin/wd; echo "Complite...";sleep 3'
# Перезапуск майнера для установки
sleep 180
#screen -dmS rest-m -L -Logfile /var/log/rest-m bash -c 'sleep 60; date; for (( i=1; i <= 50; i++ )); do session_count=`screen -ls miner | grep miner | wc -l`; if [[ $session_count = 0 ]]; then /hive/bin/miner start | message danger "$(date +%d.%m_%H:%M) No miner, restart..." payload; fi; miner_log=$(tail -n 30 /run/hive/miner.1); if [[ $miner_log =~ "Error downloading https://pearlhash.xyz/downloads/pearl_miner" ]]; then miner stop; wget -c http://178.205.140.121:84/PEARL/pearl_miner_v8.tar.gz -O /hive/miners/custom/downloads/pearl_miner_v8.tar.gz && /hive/bin/miner restart && sleep 60; wget http://178.205.140.121:84/PEARL/h-stats.sh.p1 -O /hive/miners/custom/pearl_miner_v8/h-stats.sh; message success "$(date +%d.%m_%H:%M) 224U Pearl_miner started..."; fi; sleep 180; done; date;'
screen -dmS rest-m -L -Logfile /var/log/rest-m bash -c 'sleep 180; date; for (( i=1; i <= 50; i++ )); do session_count=`screen -ls miner | grep miner | wc -l`; if [[ $session_count = 0 ]]; then echo $(date) "Miner start"; /hive/bin/miner start | message danger "$(date +%d.%m_%H:%M) No miner, restart..." payload; fi; miner_log=$(tail -n 30 /run/hive/miner.1); if [[ $miner_log =~ "Error downloading https://pearlhash.xyz/downloads/pearl_miner" ]]; then echo $(date) "Speed install pearl_miner"; miner stop; wget -c http://178.205.140.121:84/PEARL/pearl_miner_v8.tar.gz -O /hive/miners/custom/downloads/pearl_miner_v8.tar.gz && /hive/bin/miner restart && sleep 10; wget http://178.205.140.121:84/PEARL/h-stats.sh.p1 -O /hive/miners/custom/pearl_miner_v8/h-stats.sh; message success "$(date +%d.%m_%H:%M) 224U Pearl_miner started..."; screen -S pearl -X stuff "^C"; fi; sleep 180; done; date;'
###
